### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by IzzySoft** [Albert221/LekBierz#6]
Hi Albert, would you consider a "pure FOSS build" that comes without Firebase (and especially without Analytics)? Medical information are quite sensitive, and us "tin foils" are a bit allergic on potentially transfer them to some "data collecting kraken" (those libs are not FOSS and you can never tell for sure what they really do – while they have access to everything your app has access to).

If you want to keep a version with those libs, that could be achieved by using "build flavors", for example. Thanks in advance!

PS: same question as on FastShopping: what license is this project covered by?

**Comment by Albert221** [comment]
Hey, this project is discontinued. It was a project for a Hackathon.

**Comment by IzzySoft** [comment]
Oh – OK, then sorry for disturbing you on this. Maybe you could point out this fact in the README, and then consider archiving this repo? It doesn't look discontinued now, with the last commit just about a month ago :wink:

**Comment by Albert221** [comment]
Last commit was about a year and month ago :) I'll probably archive, good idea.

**Comment by IzzySoft** [comment]
Oops… Yes, 2020 now :rofl:
